[package]
name = "d12"
version = "0.1.0"
authors = ["Matyas Fodor <matyas.fodor@benevolent.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ndarray = "0.14.0"
itertools = "0.8.2"
regex = "1"
